apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "<YOURKEY>",
      "secret_access_key": "<YOURSECRET",
      "endpoint_url": "https://s3.amazonaws.com",
      "default_bucket": "modelmesh-example-models",
      "region": "us-east-1"
    }

